# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 181, 16))
        self.label_4.setObjectName("label_4")
        self.umowa = QtWidgets.QCheckBox(parent=Dialog)
        self.umowa.setGeometry(QtCore.QRect(20, 140, 171, 16))
        self.umowa.setObjectName("umowa")
        self.zapisz = QtWidgets.QPushButton(parent=Dialog)
        self.zapisz.setGeometry(QtCore.QRect(80, 190, 81, 21))
        self.zapisz.setObjectName("zapisz")
        self.imie = QtWidgets.QLineEdit(parent=Dialog)
        self.imie.setGeometry(QtCore.QRect(80, 10, 251, 21))
        self.imie.setObjectName("imie")
        self.nazwisko = QtWidgets.QLineEdit(parent=Dialog)
        self.nazwisko.setGeometry(QtCore.QRect(80, 40, 251, 20))
        self.nazwisko.setObjectName("nazwisko")
        self.nrtel = QtWidgets.QLineEdit(parent=Dialog)
        self.nrtel.setGeometry(QtCore.QRect(80, 70, 251, 20))
        self.nrtel.setMaxLength(9)
        self.nrtel.setObjectName("nrtel")
        self.pesel = QtWidgets.QLineEdit(parent=Dialog)
        self.pesel.setGeometry(QtCore.QRect(80, 100, 251, 21))
        self.pesel.setMaxLength(11)
        self.pesel.setObjectName("pesel")
        self.lista = QtWidgets.QComboBox(parent=Dialog)
        self.lista.setGeometry(QtCore.QRect(20, 240, 171, 21))
        self.lista.setObjectName("lista")
        self.zapiszplik = QtWidgets.QPushButton(parent=Dialog)
        self.zapiszplik.setGeometry(QtCore.QRect(210, 190, 81, 21))
        self.zapiszplik.setObjectName("zapiszplik")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Imię"))
        self.label_2.setText(_translate("Dialog", "Nazwisko"))
        self.label_3.setText(_translate("Dialog", "Nr tel"))
        self.label_4.setText(_translate("Dialog", "PESEL"))
        self.umowa.setText(_translate("Dialog", "Umowa o prace"))
        self.zapisz.setText(_translate("Dialog", "Zapisz"))
        self.zapiszplik.setText(_translate("Dialog", "Zapisz do pliku"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
